apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <set your role ARN here>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: <set your role ARN here> 
      username: consul-join
      groups: 
        - system:masters
  # mapUsers: |
  #   - userarn: <arn:aws:iam::111122223333:user/admin>
  #     username: <admin>
  #     groups:
  #       - <system:masters>
